// <auto-generated />
namespace GameSalesSystemMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class game_deneme_ekledim : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(game_deneme_ekledim));
        
        string IMigrationMetadata.Id
        {
            get { return "202402031550077_game_deneme_ekledim"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
