// <auto-generated />
namespace GameSalesSystemMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class picture_property_added_to_game : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(picture_property_added_to_game));
        
        string IMigrationMetadata.Id
        {
            get { return "202402061709025_picture_property_added_to_game"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
