// <auto-generated />
namespace GameSalesSystemMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NameSurname_property_added_to_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameSurname_property_added_to_User));
        
        string IMigrationMetadata.Id
        {
            get { return "202402061746264_NameSurname_property_added_to_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
