// <auto-generated />
namespace GameSalesSystemMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class cartgame_countAndamount_deleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cartgame_countAndamount_deleted));
        
        string IMigrationMetadata.Id
        {
            get { return "202402241523315_cartgame_countAndamount_deleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
